In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
b = np.array([3.4, 2, 4, 6])
b

array([3.4, 2. , 4. , 6. ])

In [4]:
c = np.array([1, 2, 3, 4], dtype = "float32")
c

array([1., 2., 3., 4.], dtype=float32)

In [5]:
d = np.zeros(10, dtype="int")
d

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
e = np.ones((3,5), dtype="float")
e

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
f = np.full((3,5), 4.1)
f

array([[4.1, 4.1, 4.1, 4.1, 4.1],
       [4.1, 4.1, 4.1, 4.1, 4.1],
       [4.1, 4.1, 4.1, 4.1, 4.1]])

In [8]:
g = np.arange(0, 20, 2)
g

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
h = np.linspace(0, 1, 5)
h

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
i = np.random.random((3,3))
i

array([[0.04668557, 0.63834846, 0.50619284],
       [0.3372694 , 0.65382427, 0.36567631],
       [0.06624931, 0.57451402, 0.77028005]])

In [19]:
x = np.random.randint(10, size = 6)
y = np.random.randint(10, size = (3, 4))
z = np.random.randint(10, size = (3, 4, 5))

print(z.ndim, z.shape, z.size)

3 (3, 4, 5) 60


In [20]:
print(z.dtype)

int64


In [23]:
j = np.array([5, 0, 3, 3, 7, 9])
print(j[0])
print(j[4])

5
7


In [24]:
print(j[-1])

9


In [27]:
k = np.array([[1,2, 3, 4], [5, 6, 7, 8]])
k

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
print(k[1,2])

7


In [31]:
k[0,0] = 12
k

array([[12,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [35]:
# x[start:stop:step]
x = np.array([1, 2, 4, 6, 8, 10, 12, 17, 19, 21, 25])
print(x[5:]) # Elements after index 5
print(x[:5]) # First five elements.
print(x[4:7]) # Middle Subarray
print(x[::2]) # Every other element.
print(x[1::2]) # Every other element starting with index 1.

[10 12 17 19 21 25]
[1 2 4 6 8]
[ 8 10 12]
[ 1  4  8 12 19 25]
[ 2  6 10 17 21]


In [37]:
print(x[::-1]) # All elements reversed.
print(x[5::-2]) # Reversed every other element from index 5.

[25 21 19 17 12 10  8  6  4  2  1]
[10  6  2]


In [39]:
x = np.arange(9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
print(x[:2, :3])# Two rows, three columns.
print("---------------------")
print(x[:3, ::2]) # All rows every other columns.

[[0 1 2]
 [3 4 5]]
---------------------
[[0 2]
 [3 5]
 [6 8]]


In [42]:
print(x[::-1, ::-1])

[[8 7 6]
 [5 4 3]
 [2 1 0]]


In [47]:
print(x[:,0])# First Column of x
print("----------")
print(x[0,:]) # First row of x

[0 3 6]
----------
[0 1 2]


In [46]:
x[:,0]

array([0, 3, 6])

In [48]:
x_sub = x[:2, :2]
print(x_sub)

[[0 1]
 [3 4]]


In [50]:
x_sub[0,0] = 22
print(x_sub)
print("-------")
print(x)

[[22  1]
 [ 3  4]]
-------
[[22  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [52]:
x_sub_copy = x[:2,:2].copy()
print(x_sub_copy)
print("---------------------")
x_sub_copy[0,0] = 41
print(x_sub_copy)
print("---------------------")
print(x)

[[22  1]
 [ 3  4]]
---------------------
[[41  1]
 [ 3  4]]
---------------------
[[22  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [54]:
grid = np.arange(1, 10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
x = np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [57]:
x = np.array([1, 2, 3])
x.reshape((1,3)) # Row vector via reshape
x[np.newaxis, :] # Row vector via newaxis

array([[1, 2, 3]])

In [59]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print(np.concatenate([x,y]))

[1 2 3 4 5 6 7 8]


In [60]:
z = np.array([9, 10 ,11, 12])
print(np.concatenate([x, y, z]))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [61]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
print(np.concatenate([grid, grid]))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [65]:
x = np.array([1, 2, 3])
#grid
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
grid = np.array([[9, 8, 7],[6, 5, 4]])
y = np.array([[10], [11]])
np.hstack([grid, y])

array([[ 9,  8,  7, 10],
       [ 6,  5,  4, 11]])

In [78]:
x = np.array([1, 2, 3, 99, 3, 2, 1])
x1, x2, x3 = np.split(x, [3,5])
print(x1)
print("-----------")
print(x2)
print("-----------")
print(x3)

[1 2 3]
-----------
[99  3]
-----------
[2 1]


In [89]:
grid = np.arange(16).reshape((4,4))
upper, lower = np.vsplit(grid, [2])
print(upper)
print("----------")
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
----------
[[ 8  9 10 11]
 [12 13 14 15]]


In [91]:
left, right = np.hsplit(grid, [2])
print(left)
print("----------")
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
----------
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
